services:
  # Servicio para Keycloak 
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: biblioteca-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=biblioteca-db
      - DB_DATABASE=bibliotecabase
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command: ["start-dev"]
    depends_on:
      - db
    networks:
      - biblioteca-network


  # Servicio para la aplicación Node.js
  app:
    build: .
    container_name: biblioteca-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=123
      - JWT_EXPIRES_IN=1d
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/bibliotecabase
    depends_on:
      - db
    networks:
      - biblioteca-network
    volumes:
      - .:/usr/src/app

  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:latest
    container_name: biblioteca-db
    environment:
      # DATABASE_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bibliotecabase
    ports:
      - "5432:5432"
    networks:
      - biblioteca-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

networks:
  biblioteca-network:
    driver: bridge

volumes:
  postgres-data:
