services:
  # Servicio para la aplicación Node.js
  app:
    build: .
    container_name: biblioteca-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=123
      - JWT_EXPIRES_IN=1d
      - DATABASE_URL=postgres://postgres:postgres@db:5432/biblioteca
    depends_on:
      - db
    networks:
      - biblioteca-network
    volumes:
      - .:/usr/src/app

  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:latest
    container_name: biblioteca-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    networks:
      - biblioteca-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  biblioteca-network:
    driver: bridge

volumes:
  postgres-data:
